### ISSUE TITLE
[BUG]TypeError: Too many parameters for typing.List; actual 2, expected 1

### ISSUE THREAD

**Issue by Nenot233** [Cvandia/nonebot-plugin-fakemsg#3]
**描述bug**
09-04 14:27:40 [ERROR] nonebot | Failed to import "nonebot_plugin_fakemsg"
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 16, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\load.py", line 48, in load_plugins
    return manager.load_all_plugins()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
 File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\plugin\manager.py", line 241, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_fakemsg\__init__.py", line 83, in <module>
    user_message: List[Tuple[str, str, Message], Any],
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\typing.py", line 312, in inner
    return func(*args, **kwds)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\typing.py", line 1144, in __getitem__
    _check_generic(self, params, self._nparams)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\typing_extensions.py", line 164, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} parameters for {cls};"
TypeError: Too many parameters for typing.List; actual 2, expected 1

**版本情况**
python:3.10
nb2.0

**Comment by Nenot233** [comment]
09-04 14:35:55 [ERROR] nonebot | Rule check failed for Matcher(type='message', module=extensive_plugin.nonebot_plugin_fakemsg).
Traceback (most recent call last):
  File "D:\BOT\zhenxun_bot\bot.py", line 22, in <module>
    nonebot.run()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 457, in check_and_run_matcher
    if not await _check_matcher(
 File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 363, in _check_matcher
    ) or not await Matcher.check_rule(bot, event, state, stack, dependency_cache):
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 303, in check_rule
    return event_type == (cls.type or event_type) and await cls.rule(
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\rule.py", line 73, in __call__
    results = await asyncio.gather(
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "D:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_fakemsg\__init__.py", line 46, in check_if_fakemsg
    if event.original_message.index("at") == 0:
  File "C:\Users\550N\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\message.py", line 307, in index
    raise ValueError(f"Segment with type {value!r} is not in message")
ValueError: Segment with type 'at' is not in message

**Comment by Cvandia** [comment]
GitHub上还在测试，用pypi的
